backend:
  name: git-gateway # https://github.com/netlify/netlify-cms
  branch: main # 要更新的分支(可选；默认为主分支)

# This line should *not* be indented
# publish_mode: editorial_workflow

# This line should *not* be indented
media_folder: "source/images/uploads" # 媒体文件将存储在图片/上载下的Repo中。
public_folder: "/images/uploads" # 上传的媒体的src属性将以/images/uploads开头。

site_url: https://ww.glwsq.cn # 网站网址
display_url: https://ww.glwsq.cn # 显示网址

# media_library:
#   name: uploadcare
#   config:
#     publicKey: 43f59da285cf51a09aa5

locale: "zh_Hans" # 语言环境 https://github.com/netlify/netlify-cms/tree/master/packages/netlify-cms-locales/src

collections:      # https://www.netlifycms.org/docs/configuration-options/#collections
  - name: "posts" # 在路由中使用，例如：/admin/collections/blog。
    label: "Post" # 在用户界面中使用
    folder: "source/_posts" # 存储文件的文件夹的路径。
    create: true # 允许用户在这个集合中创建新的文件。
    fields: # 每份文件的字段，通常是前面的内容。
      - {label: "标题", name: "title", widget: "string"}
      - {label: "分类", name: "categories", widget: "list", required: false}
      - {label: "标签", name: "tags", widget: "list", required: false}
      # - {label: "关键词", name: "keywords", widget: "list", required: false}
      - {label: "摘要", name: "excerpt", widget: "list", required: false}
      - {label: "顶部图", name: "banner_img", widget: "image", required: false} 
      - {label: "文章封面", name: "index_img", widget: "image", required: false} 
      - {label: "文章排序", name: "sticky", widget: "number", required: false}
      - {label: "发布日期", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss", hide: true, dateFormat: "YYYY-MM-DD", timeFormat: "HH:mm:ss", required: false}
      - {label: "更新日期", name: "updated", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss", dateFormat: "YYYY-MM-DD", timeFormat: "HH:mm:ss", required: false}
      - {label: "内容", name: "body", widget: "markdown", required: false}
      - {label: "永久链接", name: "abbrlink", widget: "string", required: false}
      - {label: "密码", name: "password", widget: "string", required: false}
      - {label: "主页加密说明", name: "abstract", widget: "string", required: false}
      - {label: "输入密码说明", name: "message", widget: "string", required: false}
      - {label: "评论", name: "comment", widget: "boolean", default: true, required: false}
      - {label: "隐藏", name: "hide", widget: "boolean", default: false, required: false}
      - {label: "渲染公式", name: "math", widget: "boolean", default: false, required: false}

  - name: "pages"
    label: "Pages"
    files:
      - file: "source/about/index.md"
        name: "about"
        label: "关于"
        fields:
          - {label: "标题", name: "title", widget: "string"}
          - {label: "内容", name: "body", widget: "markdown", required: false}
          - {label: "评论", name: "comment", widget: "boolean", default: true, required: false}


# 如果你不是Fluid 主题，请删除以下配置，或者对文件路径及字段进行修改
  - name: "settings"
    label: "settings"
    files:      
      - file: "source/_data/fluid_config.yml"
        name: "fluid"
        label: "Fluid 主题配置"
        editor:
          preview: true      # 是否开启编辑预览
        fields:
          - label: "导航"
            name: "navbar"
            widget: "object"
            collapsed: true   # 是否折叠显示
            fields:
              - label: "博客标题"
                name: "blog_title"
                widget: "text"
          - label: "首页"
            name: "index"
            widget: "object"
            collapsed: true   # 是否折叠显示
            fields:
              - label: "顶部图"
                name: "banner_img"
                widget: "image"
              - label: "高度"
                name: "banner_img_height"
                widget: "number"
              - label: "标语"
                name: "slogan"
                widget: "object"
                fields:
                  - label: "打字机"
                    name: "text"
                    widget: "text"
          - label: "文章页"
            name: "post"
            widget: "object"
            collapsed: true
            fields:
              - label: "顶部图(默认)"
                name: "banner_img"
                widget: "image"
              - label: "高度"
                name: "banner_img_height"
                widget: "number" 
              - label: "文章封面图(默认)"
                name: "default_index_img"
                widget: "image"
          - label: "归档页"
            name: "archive"
            widget: "object"
            collapsed: true
            fields:
              - label: "顶部图"
                name: "banner_img"
                widget: "image"
              - label: "高度"
                name: "banner_img_height"
                widget: "number"
          - label: "分类页"
            name: "category"
            widget: "object"
            collapsed: true
            fields:
              - label: "顶部图"
                name: "banner_img"
                widget: "image"
              - label: "高度"
                name: "banner_img_height"
                widget: "number"
          - label: "标签页"
            name: "tag"
            widget: "object"
            collapsed: true
            fields:
              - label: "顶部图"
                name: "banner_img"
                widget: "image"
              - label: "高度"
                name: "banner_img_height"
                widget: "number"
          - label: "关于页"
            name: "about"
            widget: "object"
            collapsed: true
            fields:
              - label: "顶部图"
                name: "banner_img"
                widget: "image"
              - label: "高度"
                name: "banner_img_height"
                widget: "number"
          - label: "友链页面"
            name: "links"
            widget: "object"
            collapsed: true
            fields:
              - label: "顶部图"
                name: "banner_img"
                widget: "image"
              - label: "高度"
                name: "banner_img_height"
                widget: "number"
              - label: "项目"
                name: "items"
                widget: "list"
                fields:
                  - {label: "网站名称", name: "title", widget: "string", required: false}
                  - {label: "网址描述", name: "intro", widget: "string", required: false}
                  - {label: "网站地址", name: "link", widget: "string", required: false}
                  - {label: "网站图片", name: "avatar", widget: "image", required: false}
          - label: "懒加载"
            name: "lazyload"
            widget: "object"
            fields:
              - label: "是否开启"
                name: "enable"
                widget: "boolean"
              - label: "仅在文章页生效"
                name: "onlypost"
                widget: "boolean"             
      - file: "netlify.toml"
        name: "redirects"
        label: "重定向"
        fields:
          - label: "项目"
            name: "redirects"
            widget: "list"
            fields:
              - {label: "原网址", name: "from", widget: "string", required: false}
              - {label: "去网址", name: "to", widget: "string", required: false}
              - {label: "强制", name: "force", widget: "boolean", required: false}

